# Generated by Django 5.1.7 on 2025-03-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_contribution_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Default GitHub Access Token', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='repository',
            name='token',
            field=models.CharField(blank=True, help_text='toke is option (it will use default token)', max_length=100),
        ),
    ]
