name: PR Management

on:
    schedule: 
        - cron: '*/30 * * * *' # cron every 20 minutes
    workflow_dispatch:

jobs:
    manage-prs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip intall -r requirements.txt

            - name: Run migrations
              run: |
                python manage.py makemigrations
                python manage.py migrate

            - name: Run PR Manager
              env:
                # Cryptographic key for Django security
                DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
                # Personal Access Token (PAT) for GitHub API
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: python manage.py runscript automated_contribution_management.sripts.pr_manager